### PR TITLE
Don't escape <= inside quotes.

### PR DESCRIPTION
**Pull request by jim-wilson**
This fixes a problem in the html output.

### CODE REVIEW

**Comment by aswaterman** [comment]
Without the escape, it renders as ⇐

It looks like the right thing to do is to write `&le;`

**Comment by jim-wilson** [comment]
The escape isn't needed inside quotes.  The github view of v-spec.adoc looks OK, but if you use asciidoc to convert to HTML, and view the HTML, you will see \<= in the HTML output which is wrong.  The github v-spec.adoc view is also correct without the escape.

The &le; looks nice in the github view of v-spec.adoc, but when I use asciidoc to convert to html, I still see &le; in the output.  Apparently, asciidoc doesn't do conversions inside quotes.  That was the same problem I was trying to fix by deleting the \ escape in the first place.  Maybe there is a way around this, but I haven't tried reading the asciidocs in full; I was trying to avoid that.

**Comment by jim-wilson** [comment]
Oops.  My previous comment only makes sense if viewed as raw text.  Trying this again...
```
The escape isn't needed inside quotes. The github view of v-spec.adoc looks OK, but if you use asciidoc to convert to HTML, and view the HTML, you will see \<= in the HTML output which is wrong. The github v-spec.adoc view is also correct without the escape.

The &le; looks nice in the github view of v-spec.adoc, but when I use asciidoc to convert to html, I still see &le; in the output. Apparently, asciidoc doesn't do conversions inside quotes. That was the same problem I was trying to fix by deleting the \ escape in the first place. Maybe there is a way around this, but I haven't tried reading the asciidocs in full; I was trying to avoid that.
```

**Comment by aswaterman** [comment]
Ah, that makes more sense.

I'm using Asciidoctor 1.5.8 and it renders into HTML correctly for me.  The documentation indicates this is the expected behavior.  Are you using a different tool or version?

**Comment by jim-wilson** [comment]
I'm using the linux asciidoc program, v8.6.10, which points at http:://asciidoc.org and says it converts asciidoc to html.  Though now I see that there is also a linux asciidoctor program, v1.5.5, which points at http://asciidoctor.org, and also claims to convert asciidoc to html.  But the two programs don't behave the same.  Maybe the differences are bugs in one or the other of the two programs.

The stuff I was fixing for asciidoc now looks OK with asciidoctor, but other stuff that looked OK with asciidoc now looks wrong.  For instance, in the note at the end of section 6.2 there is
```
`AVL <= VLMAX`
```
which was OK with asciidoc but not asciidoctor.  It needs to use &le; like the other uses.  There may be other instances in the doc.  There are also uses of >= that we might want to change to &ge; or similar for consistency.  I need a whole another patch to get the right result with asciidoctor.

We might want to document which ascii doc program we are using somewhere.

**Comment by aswaterman** [comment]
Just a couple days ago, Krste added a note to the README.md to use asciidoctor: ebfb5b81a54eb4cc5bc2858f9871e7247e026cca

**Pull request merged**
