### PR TITLE
Update README to include rvv-llvm.

### PR DESCRIPTION
**Pull request by xingmingjie**
We're working on RVV support in LLVM and would like to share it with people. The project is started from Robin Kruppe's [initial work](https://github.com/rkruppe/rvv-llvm), and now has been updated to the spec v0.8. Most of the instructions are implemented, though the work is still in progress.

### CODE REVIEW

**Comment by kito-cheng** [comment]
Ooops, we have another LLVM for rvv by @Hsiangkai: https://github.com/sifive/riscv-llvm/tree/rvv 
and here is corresponding review in upstream LLVM https://reviews.llvm.org/D69987

**Comment by xingmingjie** [comment]
Interesting. Thank you for the information. By the way, is it a good time to upstream since rvv spec is still in draft stage?

**Comment by kito-cheng** [comment]
> By the way, is it a good time to upstream since rvv spec is still in draft stage?

I don't expect it would be accepted/merged before standardized personally, but I think it would be great if we can get review comment earlier and prevent rework amount different groups :)  

Another example is B-extension for LLVM, Embecosm also publish their patch on review system:
https://reviews.llvm.org/D65649
https://reviews.llvm.org/D67348

**Comment by xingmingjie** [comment]
Yes, sounds reasonable. So, I suggest put all of these helpful additional rvv resources in README.

**Pull request closed without merging**
