### PR TITLE
ISA formats in WaveDrom format

### PR DESCRIPTION
**Pull request by drom**
* Converted all ISA formats into WaveDrom files
  * Added image links to WaveDrom rendering server

note:
Before pulling this change replace: `github/wavedrom/riscv-v-spec` -> `github/riscv/riscv-v-spec` in `v-spec.adoc`

### CODE REVIEW

**Comment by aka-sps** [comment]
~~~~
asciidoctor: WARNING: allow-uri-read is not enabled; cannot embed remote image: https://svg.wavedrom.com/github/wavedrom/riscv-v-spec/master/assets/VLxU.json5
asciidoctor: WARNING: image to embed not found or not readable: https://svg.wavedrom.com/github/wavedrom/riscv-v-spec/master/assets/VLxU.json5
...
Prawn::Errors::CannotFit
  Use --trace for backtrace
~~~~

Extra/dangerows external dependency: https://svg.wavedrom.com
What about build w/o network access?

**Comment by drom** [comment]
Strange. I am getting `v-spec.html` file by running the following command with on warnings.

```
asciidoctor.ruby2.6 v-spec.adoc
```

**Comment by aka-sps** [comment]
> Strange. I am getting `v-spec.html` file by running the following command without any warnings.

html5 - OK. Try to check pdf, xhtml5, docbook5, docbook45, manpage, etc..

At first glance: where are the following XML declarations?

~~~~
<?xml version="..." encoding="..." standalone="..."?>
<svg  version="1.0" ... xml:space="...">
...
~~~~

Encoding - first of all. Proper file extension - 2nd.

And last but not least: how to generate a picture **before** or **without** publication?

Unsuitable solution.
Dependence on untested additional tools is highly undesirable.

**Comment by drom** [comment]
> html5 - OK. Try to check pdf, xhtml5, docbook5, docbook45, manpage, etc..
> At first glance: where are the following XML declarations?
> 
> ```
> <?xml version="..." encoding="..." standalone="..."?>
> <svg  version="1.0" ... xml:space="...">
> ...
> ```
> Encoding - first of all. Proper file extension - 2nd.

Why do we need to support all these targets?

**Comment by aswaterman** [comment]
We don't.  PDF and HTML are sufficient.  That's already a significant improvement over the base ISA, which effectively only supports PDF, as the other LaTeX backends barely work.

**Comment by aka-sps** [comment]
> PDF and HTML are sufficient.

Unfortunately, there are problems with PDF. 
And many users will have online problems with 金盾工程.

First of all, check a solution based on handicraft tools before use: 

- build offline
- build from uncommited draft sources
- build all target formats
- build with different platforms
- follow SVG standards

> That's already a significant improvement over the base ISA, which effectively only supports PDF, as the other LaTeX backends barely work.

`docbook` can give even more significant improvements with more standard tools.

**Comment by drom** [comment]
I have fixed an official documentation generator. it can build HTML and PDF offline.
Also, it can build under Linux, OSX, and Windows.

**Pull request closed without merging**
