### PR TITLE
Issue #220 State when on 5-bit immediate is sign extended to SEW or is unsigned 

### PR DESCRIPTION
**Pull request by David-Horner**
Issue #220

### CODE REVIEW

**Comment by David-Horner** [comment]
I hope I have done this correctly. It is only the 5-bit immediate I intend to address.

**Comment by aswaterman** [comment]
Shift amounts in the “clip” instructions, too, right?

**Comment by David-Horner** [comment]
Yes. I considered it included.

**Comment by aswaterman** [comment]
I've already seen one implementation get this wrong for clips but not shifts, so I think it would be prudent not to leave it implicit that clips are shifts.  I'll make that change as part of merging this PR.

**Comment by David-Horner** [comment]
Thank you.

**Pull request merged**
