### PR TITLE
fixed typo in vmfeq and use "mask anding" to reduce instruction count.

### PR DESCRIPTION
**Pull request by David-Horner**
Signed-off-by: David Horner <ds2horner@gmail.com>

### CODE REVIEW

**Comment by aswaterman** [comment]
I had thought about this formulation, but unfortunately it is not correct with respect to signaling NaNs.  If va[i] contains a quiet NaN and vb[i] contains a signaling NaN, then we should raise the invalid exception, but this formation will suppress it.

**Comment by David-Horner** [comment]
Well, at least I caught the typo.



On Fri, Aug 16, 2019, 17:34 Andrew Waterman, <notifications@github.com>
wrote:

> I had thought about this formulation, but unfortunately it is not correct
> with respect to signaling NaNs. If va[i] contains a quiet NaN and vb[i]
> contains a signaling NaN, then we should raise the invalid exception, but
> this formation will suppress it.
>
Right. Thanks again.

**Comment by aswaterman** [comment]
Yeah, thanks for that, I'll manually fix it upstream.

**Comment by aswaterman** [comment]
Also, FWIW, GCC's default behavior is to ignore the existence of signaling NaNs, so this more efficient code sequence that you've proposed will actually get some play.  Since it has been suggested a few times, I'm adding a note to the spec.

**Comment by David-Horner** [comment]
On Fri, Aug 16, 2019, 19:57 Andrew Waterman, <notifications@github.com>
wrote:

> Also, FWIW, GCC's default behavior is to ignore the existence of signaling
> NaNs, so this more efficient code sequence that you've proposed will
> actually get some play. Since it has been suggested a few times, I'm adding
> a note to the spec.
>
For isgreater and isless setting the mask with vmfne v0, va, vb will
suffice as the NANs and equals will be cleared in the mask (All elements
will be checked with signaling  NANs reported ) leaving only the unequal
non-NAN to be compared in the vmfgt v0, va, vb, V0.t instruction.

Further supporting the decision to eliminate vmford.

**Comment by aswaterman** [comment]
FNE matches the C operator !=, so unlike the other comparisons, it sets the
mask bit high on NaN inputs.

But either way, the quiet comparisons are unusual enough that being able to
implement them in 4 instructions (or 3 when disregarding signaling NaNs, as
GCC does) is OK.

**Pull request closed without merging**
