### PR TITLE
Mask and vl dependencies are control dependencies for RVWMO purposes

### PR DESCRIPTION
**Pull request by aswaterman**

### CODE REVIEW

**Comment by aswaterman** [comment]
cc @daniellustig

**Comment by aswaterman** [comment]
A related question is, should the same apply to `vstart` and `vl`?  This relaxation would also match the corresponding scalar code, where the loop-head and loop-closing branches only imply control dependencies on the loop body.

**Comment by David-Horner** [comment]
As Krste pointed out elsewhere, vl tail is a shorthand for masking each element of the tail.
So, I agree that vl is implicit included and should be explicitly.

I believe vstart is a different beast. It should not and cannot in general be used to mask initial elements.
The implementation is allowed to trap if there is an attempted to be used in this manner; it is not portable.

In another any other context than resumption of an exception it should be either defined as indeterminate, but better that the dependencies that would have been there if vstart did not excluded them in a "restart" are assumed to be there.

My position is even more than this, it should act as an anti-mask, that even though the elements would otherwise have been masked out (with the current mask values), if they are within vstart "already processed" range the dependency should be assumed.

General rule:When in doubt endorse the worst case. 
The rules could be relaxed later, but if we choose a more relaxed than useful and practical we will have to suffer for it until at least a flag day event.

**Comment by David-Horner** [comment]
I have some difficulty with the implied distinction between control and data dependencies.
The reality is RVWMO ordering applies whether you call a dependency data or control.
It is the situations that causes the dependency to arise that determines the nomenclature.
Mask effects can be formulated as either:
A data dependency:
vd(x) =  (op (vs1(x),vs2(x)) AND (signextend(mask(x)) OR (vd(x) AND signextend(~mask(x)))

or control:, 
vd(x) = if (mask(x) == 1) then (op (vs1(x),vs2(x)) else vd(x) fi;

The vd result is dependent upon mask either way.

The true distinction is not mask dependency, but rather the data dependency of the vd(x) element on the other instruction sources (vs1, vs2, rs2, etc.) or no data dependency on those sources (but mask alone).

The other substantial challenge is that these mask dependencies are not syntactic but rather true data-value dependencies.
I have no idea how mature the analysis of these is in academia or in the field.

**Comment by aswaterman** [comment]
The PPO rules are weaker for control dependencies than data dependencies.  In particular, program order isn't preserved for control -> load dependencies, but is preserved for data -> load dependencies.

**Comment by David-Horner** [comment]
The masked vl instruction itself, indeed all masked instructions, can be interpreted as a two stage process, such that even with a data dependency to the vd allocation, there is no data dependency to the load (or other op). Similarly, there is no control dependency to the load per se, but rather to the vd allocation.

The instruction itself starts without a control dependency in the mask.
For instruction completion, the data dependency to mask is present.
So, either way the absence of a dependency allows at least as early a load as it would with a control dependency.

If however, the masked load is considered a indivisible instruction, then the only possible way of defining the dependency of the mask on the instruction as a whole is a data dependency.

In any case the control determination ( within the masked instruction) is not syntactic but data-value. This type of determination is not defined in RVWMO, and so I suggest its PPO rule cannot be applied as is, not without special consideration.

**Comment by aswaterman** [comment]
I'm saying it's equivalent to `bnez mask_bit_value, 1f; load element; 1:`

**Comment by David-Horner** [comment]
On Sun, Jul 19, 2020, 23:16 Andrew Waterman, <notifications@github.com>
wrote:

> I'm saying it's equivalent to beqz mask_bit_value, 1f; load element; 1:
>
> —
>
It could equally be equivalent to
load into tmp; beqz mask, 1f; vd = tmp; 1:
The load is then allowed to start even earlier.

But we are in agreement that envisioning the masked instructions as two
distinct parts to identify dependencies is a correct approach.

The load could be further subdivided and parts put under mask such as TLB
load and page request.

I believe we are in the realm of microarch as there are many valid
tradeoffs.

However, even for your example determining the beqz is not syntactic and so
outside RVWMO.

**Comment by aswaterman** [comment]
My formulation _is_ a syntactic control dependency on the instruction that produced the mask value, exactly as defined in the RVWMO spec: https://github.com/riscv/riscv-isa-manual/blob/40583f4fe0f53a2173577b5d035fcfadf8023941/src/rvwmo.tex#L126

**Comment by daniellustig** [comment]
I agree with @aswaterman's view that in principle, the dependencies on `vl`, the mask registers, and possibly other registers can be treated as control dependencies from an RVWMO perspective.  However, I'd also argue that the current RVWMO text linked in the previous comment doesn't quite capture this properly, because in the code there wouldn't actually be a branch or jump instruction in between.  (Maybe that's what @David-Horner is objecting to?)

We could adjust that RVWMO text to also include "control source registers", similar to how syntactic address and data dependencies are defined:

"$b$ has a {\em syntactic control dependency} on $a$ if there is an instruction $m$ program-ordered between $i$ and $j$ such that $m$ is a branch or indirect jump and $m$ has a syntactic dependency on $i$, or if $r$ is a control source register for $j$ and $j$ has a syntactic dependency on $i$ via source register $r$."

...then, define `vl`, the mask registers, and whatever else to be control source registers for the appropriate mask instructions.

(Or, possibly even better: maybe we do a little more rewriting so that even branches and indirect jumps are defined in terms of control source registers too.  That might simplify the end result a little bit.  I'll think about that some more.)

Thoughts?

**Comment by David-Horner** [comment]
Pedantic is the nature of these WMO musings; so, I expect you all  will for give me for splitting hares (bunny punny intended) in hacking apart the RVWMO wording in addition to the (combined) mask-load construct.

I started this before Daniels response, so I will leave it substantially unchanged, but add Daniel specific responses(s).

Relevant 14.1 Syntactic Dependencies:

>Instruction j has a syntactic dependency on instruction i via destination register s of i and source
register r of j if ....:
>There is an instruction m program-ordered between i and j such that all of the following hold:
>1. j has a syntactic dependency on m via destination register q and source register r
>2. m has a syntactic dependency on i via destination register s and source register p
>3. m carries a dependency from p to q ....
>let a and b be two memory operations, and let i and j be the
instructions that generate a and b, respectively .....
>b has a syntactic control dependency on a if there is an instruction m program-ordered between i
and j such that m is a branch or indirect jump and m has a syntactic dependency on i

RVWMO exclusively considers the RISCV single function per instruction register load/store construct and source to destination 
It provides chapter 14.3 source to destination dependency carrying details for all RV32/64IMAFDZicsr  instructions.  

>... formulation is a syntactic control dependency on the instruction that produced the mask value, exactly as defined in the RVWMO spec

RVWMO does not anticipated embedded branch instructions.
Specifically for 3 above, how does one interpret carrying a dependency within an instruction?
Implicit in the formulation “equivalent to beqz mask_bit_value, 1f; load element; 1:” is a special provision outside the RVWMO model. 

Daniel’s response appears to take a different tact.
That modifies the control dependency rule rather than rule 3.

I do agree that in general this is a preferred formulation, and is close to what  I would formulate for the masked vector store. (This is I believe Daniel’s generalization suggestion).

Even if, this formulation gives rise to an identical in nature syntactic control dependency for the load on the instruction that sets the mask, is this desirable? 

The alternative formulation:
load element into tmp; beqz mask_bit_value, 1f; vd element is assigned tmp value; 1:
has no control dependency on the mask setting for the load (only existing control dependencies apply).

Provisioning that zero mask elements can have their reads vacated (including participating in rule # 2) is the other half of what I was getting at.

**Comment by aswaterman** [comment]
@daniellustig I suppose I was skipping a step and was thinking of defining vector instructions as equivalent to a sequence of scalar instructions, including branches for masking and vl.  The existing PPO machinery would then take care of the rest.  Your more direct approach makes sense and might end up being cleaner.

**Pull request merged**
