### PR TITLE
AMOs and indexed loads/stores use XLEN-bit indices, no matter SEW

### LINKED ISSUE #381: Supporting XLEN-bit Scatter/gather/AMO indices if sub-SEW memory accesses are removed
See #306 for context on supporting indexed memory accesses with different index and data widths.

Under the no-sub-SEW-memory-access regime proposed #362, we'll need a new way to decouple the index width from the data width for indexed memory accesses.  By far the most important case to support is XLEN-bit indices (so they can hold general pointers) and SEW-bit data.  While this isn't especially efficient for narrow data, at least it is complete.

My proposal is to redefine the VLXE/VSXE/VAMO*E instructions to always use XLEN-bit indices, regardless of SEW.  Assuming ELEN=XLEN, these instructions access the index vector as though LMUL were increased by a factor of (XLEN/SEW), so they have the constraint that (XLEN/SEW)*LMUL <= 8.

The fractional-LMUL concept that underpins #362 pairs well with this proposal.  Without it, index vectors would always take at least (XLEN/SEW) vector registers, which would be particularly painful for SEW=8 on RV64.

A future 64-bit encoding can fully decouple the index width to support narrower indices when appropriate.  While the 32-bit encoding can support instructions that have SEW-sized indices and data, as the current VLXE/VSXE/VAMO*E instructions do, it's not clear to me they're generally useful enough.

### PR DESCRIPTION
**Pull request by aswaterman**
Resolves #381

### CODE REVIEW

**Comment by JamesKenneyImperas** [comment]
Andrew, I think this introduces new vector register overlap constraints that need to be documented as part of the change.

**Comment by aswaterman** [comment]
@JamesKenneyImperas yes indeed, fixed (I think).

**Comment by JamesKenneyImperas** [comment]
Andrew, another issue that requires clarification: what happens for implementations where `XLEN`>`ELEN`? We have had several enquiries about implementations where `XLEN`=64 and `ELEN`=32, for example.

One solution could be:
1. Define new `ILEN` (index length) as `ILEN=min(XLEN,ELEN)`;
2. Recast your definition to use `ILEN` instead of `XLEN` throughout;
3. Specify that if `ILEN`<`XLEN`, the intermediate index is sign-extended to `XLEN`.

There are various other possibilities which seem worse to me:
1. Require `ELEN`>=`XLEN `in all implementations;
2. Make these Illegal Instructions if `XLEN`>`ELEN`;
3. Use the preferred solution above, but fix `ILEN` to the always-supported value 32;
4. Specify that an element size of `XLEN` must be supported in this special case even if `XLEN`>`ELEN` in general.

**Comment by aswaterman** [comment]
We definitely aren't trying to preclude machines with XLEN > ELEN.  Your IDXLEN proposal seems workable.  (Note, ILEN is already used to refer to the width of the widest instruction the machine supports.)

Regarding your less-preferred alternatives:
- Alternative 4 actually seems preferable to me.  For implementations whose spatial datapath width is already greater than ELEN, the main cost in increasing ELEN is in building functional units whose costs scale superlinearly in ELEN.  In that context, supporting larger ELEN only for these instructions is inexpensive.  (For machines where XLEN > ELEN and the spatial datapath width is only ELEN, there is a cost increase, but such machines seem quite contrived to me.)
- Platforms are always free to opt for alternatives 1 or 2, regardless of what we specify here.
- Alternative 3 is a non-starter, since that precludes gathering from arrays of pointers.

I would like @kasanovic and the rest of the TG to choose between your proposal (define IDXLEN = min(XLEN, ELEN) and use that), or your alternative 4 (support wider ELEN for these instructions only).

**Comment by JamesKenneyImperas** [comment]
I modified my earlier post to use `IDXLEN` to avoid confusion.

Note that for alternative 4, in a legal-but-perhaps-unlikely implementation with `XLEN`=64, `ELEN`=32 and `SLEN`=32 the index value will be distributed across vector registers. I don't know if this is of any relevence from a hardware perspective but I thought it was worth mentioning.

**Comment by David-Horner** [comment]
@JamesKenneyImperas 
> One solution could be:
> 
>  1   Define new IDXLEN (index length) as IDXLEN=min(XLEN,ELEN);
>  2   Recast your definition to use IDXLEN instead of XLEN throughout;
>  3   Specify that if IDXLEN<XLEN, the intermediate index is sign-extended to XLEN.

I prefer this approach, however I disagree with point 3.
 I believe the current choice for zero-extension is preferred, conceptually easier for most applications. To handle as a signed index  subtract 2 ** (ELEN -1) from the base register and add to the vector elements.

@aswaterman 

> ... Alternative 4 actually seems preferable to me, though. 

> `4. Specify that an element size of XLEN must be supported in this special case even if XLEN>ELEN in general`.

I see this as problematic.

**In practice XLEN>ELEN means XLEN=2 * ELEN.** [[For current targets, XLEN = 4 * ELEN is not a likely design point . With XLEN=64 an ELEN of 16 is improbably, and an ELEN=8 is ridiculous regardless of XLEN.]]

As much as support for index of pointers is desirable, is it practical when XLEN=2 * ELEN?
**Alternative 4 does not have supporting instructions/modes to set up the indexes.** This would require software to manipulate high-low element pairs if XLEN = 2 * ELEN. This is a high cost for the typical case when providing an offset rather than an address.

 In many cases these high end elements value would be the same for all pairs. In which case IDXLEN = ELEN (alternative 1)  is not problematic, just add the upper constant to the base register. 


**I will suggest a escape mechanism from IDXLEN, rs1 is zero.**

rs1=0  zero.can be reserved in all load/store.
But in indexed/AMO it means vs2 is an XLEN pointer rather than an IDXLEN offset..

**Comment by aswaterman** [comment]
@David-Horner Yes and no... you've already presupposed 32-bit indices are sufficient for these systems, so there isn't any need to provide the full arithmetic set for SEW=64.  You just need the sign-/zero-extension operations, whose cost is trivial.  You can do all the computation with SEW=32, then widen the result to 64 bits, then do an indexed memory access.

**Comment by David-Horner** [comment]
> You just need the sign-/zero-extension operations, whose cost is trivial. You can do all the computation with SEW=32, then widen the result to 64 bits, then do an indexed memory access.

Are you proposing augmenting Alternative 4 to include that extend to XLEN instruction?
It appears a relatively high incremental cost. Rather the expansion can be done in software.

I don't think there needs to be such a presupposition.
It will only be in the context of a finalized RVV design that hardware designers will determine if ELEN < XLEN meets their target audience. Handling 64-bit indices in software (using ELEN operations) may be sufficient when there is a mechanism (pointers) to provide the actual load/store/AMO.
For XLEN=64 ELEN=32:
64bit arithmetic has many software approaches, but none are low overhead for ELEN=32 (especially as element-pairs) . Thus such cost could be paid for pointers only, when 32-bit offsets are sufficient.

**Comment by knightsifive** [comment]
Some arguments in this discussion leverage the possibility that ELEN < XLEN; whether or not this is actually permitted is being discussed over at #404.

**Comment by David-Horner** [comment]
@David-Horner  

> Are you [@aswaterman] proposing augmenting Alternative 4 to include that extend to XLEN instruction?

Over at #404 relaxing widening constraints provides that function: 

Allowing 2 * ELEN is low cost for integer widening operations add/subtract, somewhat more so for multiply/multiply-add. The tie-in to #401 is that for XLEN = 2 * ELEN, these 2 * ELEN widening operations allow building complex XLEN offsets based on successive multiplication and additions of matrix indices.

This option of using Alternative 4 with XLEN = 2 * ELEN widening ops ,  and my proposal for rs1=x0 to differentiate between offsets and pointers are not mutually exclusive but they provide some weighing towards Andrew's proposal.

**Comment by aswaterman** [comment]
Superseded by recent changes.

**Pull request closed without merging**
