### PR TITLE
Further relax tail handling for mask logical instructions

### PR DESCRIPTION
**Pull request by aswaterman**
This is a generalization of fd4565e18d882d3ad2df8592be81034bafac1b71 in response to @JamesKenneyImperas' comment https://github.com/riscv/riscv-v-spec/commit/fd4565e18d882d3ad2df8592be81034bafac1b71#commitcomment-51940463

### CODE REVIEW

**Comment by JamesKenneyImperas** [comment]
Hello Andrew,

I'm wondering if we are opening an unintentional hole here that encourages users to misuse mask logical instructions in non-portable ways. For example, suppose that an algorithm is operating with `EEW=32` / `VLMUL=8`, and there is a requirement to zero out the `v7` part of a value held in `v0...v7` for some reason. If their implementation supported it, they might be tempted to do this using `vmxor.mm v7, v7, v7`, even though this is not portable. What do you think?

**Comment by aswaterman** [comment]
@JamesKenneyImperas I'm not espousing an opinion by making this PR; I'm just writing up my best understanding of the TG's intent.  I'm quite confident they would not have wanted fd4565e18d882d3ad2df8592be81034bafac1b71 if not for this piece.

But, since you asked: my opinion is that this portability hole is not materially worse than the other agnosticism-related holes, despite your valid example.

**Comment by David-Horner** [comment]
Is the cart not once again before the horse in pushing before discussing?

I quote @aswaterman   " I'm just writing up my best understanding of the TG's intent. I'm quite confident they would not have wanted fd4565e if not for this piece." related to push related to issue  #639.

These two pulls would have been neatly tied to a discussion if  issue #639 was left open for the discussion.
Github is geared to that workflow.
In addition, an "issue discussion" is more clearly about the issue [unsurprisingly], its possible resolution and its eventual application to the repository.

This was not just a typo nor a reformatting fix, but rather a substantive design component that deserves more support than being embedded into a pull/push.

As always, up front design time helps to eliminate "test" churn and post implementation bugs. [product life-cycle].
Yes, everyone will eventually see the concern in the ratification text, but identifying and addressing the issue at design time is much much preferred.
And that is best done, IMHO. through issues not naked pull/pushes. 

And to quote @aswaterman again: "this portability hole is not materially worse than the other agnosticism-related holes".

The discussion for that shouldn't be on a pull request.
In a perfect world it would be an issue discussion that remained open until resolved to the satisfaction of all.

**Comment by aswaterman** [comment]
How about we all stop shooting from the hip.  My response to some of of these concerns is on another thread: https://github.com/riscv/riscv-v-spec/commit/fd4565e18d882d3ad2df8592be81034bafac1b71#commitcomment-51979075

**Comment by kasanovic** [comment]
This does match the TG intent, but it's noted that the vms*f.m instructions can also be added to this set.

**Pull request merged**
